# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: A:/Facultate/Labs/SSC/Laboratorul9/Hardware/constrs/zyboz20.xdc

# Block Designs: bd/hdmi/hdmi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi || ORIG_REF_NAME==hdmi} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_processing_system7_0_0/hdmi_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_processing_system7_0_0 || ORIG_REF_NAME==hdmi_processing_system7_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_dynclk_0_0/hdmi_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_axi_vdma_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_v_tc_0_0 || ORIG_REF_NAME==hdmi_v_tc_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_rgb2dvi_0_0/hdmi_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axis_subset_converter_0_0/hdmi_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axis_subset_converter_0_0 || ORIG_REF_NAME==hdmi_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_xlconstant_0_0/hdmi_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_xlconstant_0_0 || ORIG_REF_NAME==hdmi_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_mem_intercon_0/hdmi_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_xbar_0 || ORIG_REF_NAME==hdmi_xbar_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_ps7_0_axi_periph_0/hdmi_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_ps7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_rst_ps7_0_100M_0 || ORIG_REF_NAME==hdmi_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_gpio_btn_and_sw_0/hdmi_axi_gpio_btn_and_sw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axi_gpio_btn_and_sw_0 || ORIG_REF_NAME==hdmi_axi_gpio_btn_and_sw_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axi_timer_0_0 || ORIG_REF_NAME==hdmi_axi_timer_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_pc_0/hdmi_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_auto_pc_0 || ORIG_REF_NAME==hdmi_auto_pc_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_pc_1/hdmi_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_auto_pc_1 || ORIG_REF_NAME==hdmi_auto_pc_1} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_gameLogic_0_0/hdmi_gameLogic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_gameLogic_0_0 || ORIG_REF_NAME==hdmi_gameLogic_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_gpio_0_0/hdmi_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axi_gpio_0_0 || ORIG_REF_NAME==hdmi_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_gpio_0_1/hdmi_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_axi_gpio_0_1 || ORIG_REF_NAME==hdmi_axi_gpio_0_1} -quiet] -quiet

# XDC: a:/Facultate/Labs/SSC/TicTacToe/Hardware/zybo_hdmi.gen/sources_1/bd/hdmi/hdmi_ooc.xdc
