# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0.xci
# IP: The module: 'hdmi_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.gen/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.gen/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.gen/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.srcs/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0.xci
# IP: The module: 'hdmi_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.gen/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.gen/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: a:/Facultate/Labs/SSC/Laboratorul9/Hardware/vivado_project/zybo_hdmi.gen/sources_1/bd/hdmi/ip/hdmi_rst_ps7_0_100M_0/hdmi_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
